### PR TITLE
Completed css-two-column-layout challenge

### PR DESCRIPTION
**Pull request by hollyphung95**
Screenshot 2023-01-27 at 12 07 17 PM

### CODE REVIEW

**Review by robgmerrill — CHANGES_REQUESTED** [review]
Great start! It appears as though the font families aren't being applied to match the design. Let me know if you are having any problems applying those!

**Comment by robgmerrill** [comment]
Also, note the each section title should be slightly lower than the image.

**Comment by hollyphung95** [comment]
Screenshot 2023-01-27 at 2 11 53 PM

**Review by robgmerrill — APPROVED** [review]
👍

**Pull request merged**
